PROGRAM = my_asm_test
PROGRAM_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
EXTRA_SRCS := my_asm_test_impl.S
IBEX_COMMON_DIR := $(PROGRAM_DIR)/../../dut/ibex/examples/sw/simple_system/common

include $(IBEX_COMMON_DIR)/common.mk
